<?php

return [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName'  => false,
    'rules'           => [
        '//docs.vspu.ru/'                                          => '/program/index',
        '//docs.vspu.ru/edu-programs'                              => '/program/index',
        '//docs.vspu.ru/edu-programs/xml'                          => '/program/xml',
        '//docs.vspu.ru/edu-program/<id:\d+>'                      => '/program/edu-program',
        '//docs.vspu.ru/<controller:(program)>/<id:\d+>'           => '/<controller>/view',
        '//docs.vspu.ru/<controller:(program)>/<id:\d+>/<action>'  => '/<controller>/<action>',
        '//docs.vspu.ru/<action:.*>'                               => '/program/index',
        '/login'                                                   => '/auth/login',
        '/signup'                                                  => '/registration/signup',
        '/reset'                                                   => '/auth/request-password-reset',
        '/recovery'                                                => '/auth/reset-password',
        '/confirm'                                                 => '/registration/confirm',
        '/redirect/<name>'                                         => '/site/redirect',
        '/attendance/<id:\d+>/on/<onDate:\d{8}>'                   => '/attendance/view-date',
        '/attendance/<id:\d+>/on/<onDate:\d{8}>/refresh'           => '/attendance/refresh',
        '/attendance/history/<onDate:\d{8}>'                       => '/attendance/history',
        '<controller:.*>/<id:\d+>'                                 => '<controller>/view',
        '<controller:.*>/<id:\d+>/<action>'                        => '<controller>/<action>',
        '/form1'                                                   => 'takedatam/default/index',
        '/form2'                                                   => 'takedatam/default/form2',
        '/form3'                                                   => 'takedatam/default/form3',
        '/form4'                                                   => 'takedatam/default/form4',
        '/paid_edu'                                                => 'takedatam/default/paidedu',
        '/grantsold'                                               => 'takedatam/default/grantsold',
        '/grants'                                                  => 'takedatam/default/grants',
        '/document'                                                => 'takedatam/default/document',
        '/common'                                                  => 'takedatam/default/common',
        '/eduStandarts'                                            => 'takedatam/default/edustandarts',
        '/inter'                                                   => 'takedatam/default/inter',
        '/budget'                                                  => 'takedatam/default/budget',
        '/objects'                                                 => 'takedatam/default/objects',
        '/catering'                                                => 'takedatam/default/catering',
        '/education'                                               => 'takedatam/default/education',
        '/upload'                                                  => 'takedatam/default/upload',
        '/deleteform2'                                             => 'takedatam/default/deleteform2',
        '/deleteform3'                                             => 'takedatam/default/deleteform3',
        '/deleteform4'                                             => 'takedatam/default/deleteform4',
        '/delete_paid_edu'                                         => 'takedatam/default/deletepaidedu',
        '/delete_grants'                                           => 'takedatam/default/deletegrants',
        '/delete_document'                                         => 'takedatam/default/deletedocument',
        '/delete_inter'                                            => 'takedatam/default/deleteinter',
        '/delete_budget'                                           => 'takedatam/default/deletebudget',
        '/delete_objects'                                          => 'takedatam/default/deleteobjects',
        // [
        //     'class' => 'yii\web\GroupUrlRule',
        //     'prefix' => 'takedatam',
        //     'rules' => [
        //         'default' => 'default/index'
        //     ],
        // ],
    ],
];